<?php

namespace AppBundle\Repository;

/**
 * lendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lendRepository extends \Doctrine\ORM\EntityRepository
{
}
