<?php

namespace AppBundle\Repository;

/**
 * LendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LendRepository extends \Doctrine\ORM\EntityRepository
{
}
